version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: ["gunicorn", "chess5.wsgi:application", "--bind", "0.0.0.0:8000"]
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - web
