image: docker:19.03.12

services:
  - docker:19.03.12-dind

stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

before_script:
  - echo $GCP_SERVICE_KEY | docker login -u _json_key --password-stdin https://gcr.io

build_job:
  stage: build
  script:
    - echo "Building the application"
    - docker build -t gcr.io/mm-chess-397014/mm-chess-app:latest .

deploy_job:
  stage: deploy
  script:
    - echo "Deploying the application"
    - docker push gcr.io/mm-chess-397014/mm-chess-app:latest
